spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: production
---

spring:
  messages:
    basename: lang/res
    fallback-to-system-locale: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pokak
    username: postgres
    password: NOVIANTO

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 51284225991-rr1o1uh408ca94g8pg08luq5oofd5a88.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 911499133519740
            clientSecret: d66724e48c9e216b867277838aa7610b
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: Iv1.499c962a4f90b584
            clientSecret: c02470b06cb8c386624f46a14c30e03876e74542
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,name,email,picture.width(250).height(250)
  mail:
    host: smtp.gmail.com
    port: 587
    username: mnoviantoanggoro@gmail.com
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    #      ssl.trust: ${MAIL_SERVER_HOST}
    password: aeufnalrxplogcbb
app:
  appName: Pokak Herbal
  frontEndUri: http://localhost:3000
  deleteExpiredTokensDelayMsec: 30000 # 30 seconds
  allowedOrigins:
    - http://localhost:3000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
  accountActivationUri: http://localhost:3000/activate-account
  emailChangeConfirmationUri: http://localhost:3000/confirm-email-change
  passwordResetUri: http://localhost:3000/password-reset
  auth:
    tokenSecret: w1y4t4s0ftw4r3d1g1t4l
    accessTokenExpirationMsec: 300000 # 5 minutes
    refreshTokenExpirationMsec: 900000 # 15 minutes
    verificationTokenExpirationMsec: 60000 # 1 minute
  max-request-size: 200000000 # 200 MB

#server:
#  tomcat:
#    connection-timeout: 5s
